name: Build and Publish Artifacts

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "0 0 1 * *" # first day of the month at midnight UTC

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore BDInfoCli.sln
        shell: cmd

      - name: Build solution (Release)
        run: msbuild BDInfoCli.sln /p:Configuration=Release /p:Platform="Any CPU"
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BDInfoCLI-Release
          path: BDInfo/bin/Release/
          retention-days: 30
